### ISSUE TITLE
checker: handle getattack failures properly

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/service-wasp#2]
```
Task finished INTERNAL_ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/enochecker_async/enochecker.py", line 68, in post
    await checker.getflag(scoped_logger, checker_task, collection)
  File "checker.py", line 78, in getflag
    if matches["attack"][flag_field] != task.flag:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Trolldemorted** [comment]
should work now
